version: "3.8"
services:
  backend:
    container_name: backend-example
    ports:
      - 2001:2000
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
